### ISSUE TITLE
Values list append and extend features request

### ISSUE THREAD

**Issue by sanjaysrikakulam** [lucadiliello/compressed-dictionary#22]
Hi,

Thanks for developing this. I was looking for a compressed dictionary and found this. 

When testing, I have a few requests.

1) Readme update: 

This does not work, 
`from create_pretraining_dataset.utils import CompressedDictionary`
Should be
`from compressed_dictionary.compressed_dictionary import CompressedDictionary`

2) A append and extend functionality

```
from compressed_dictionary.compressed_dictionary import CompressedDictionary

d = CompressedDictionary()
d[1] = [1, 2, 3]

# Feature request:
d[1].append(4)

# and
d[1].append([4, 5, 6])

# and
d[1].extend([7, 8, 9])
```

Thank you!

**Comment by lucadiliello** [comment]
Hi @sanjaysrikakulam , thank you for using `compressed-dictionary`.

1) I cannot reproduce your bug with the import of `compressed_dictionary`, I tried with a new env end everything worked fine.
2) The problem with you features request is that `append` and `extend` are acting on the results of `d[1]` and not on the `compressed-dictionary`. If `d[1]` returns your list `[1, 2, 3]`, `extend` will act on this list and not on `d`.
I could just suggest to use `d[1] += [4]` or `d[1] += [7, 8, 9]` as a workaround for your problem.

**Comment by sanjaysrikakulam** [comment]
Hi @lucadiliello , thank you for your reply.

1. when I use the other import you have given in README I get `ModuleNotFoundError: No module named 'create_pretraining_dataset'` error
2. This workaround would work as well. 

Thank you!
